// frontend/src/components/Layout.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <nav class="bg-white shadow-sm border-b border-gray-200">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
          <div class="flex">
            <div class="flex-shrink-0 flex items-center">
              <router-link to="/dashboard" class="text-2xl font-bold text-primary-600">
                Mahsoul
              </router-link>
            </div>
            <div class="hidden sm:ml-6 sm:flex sm:space-x-8">
              <router-link
                v-for="item in navigation"
                :key="item.name"
                :to="item.to"
                class="inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium transition-colors"
                :class="[
                  $route.path.startsWith(item.to)
                    ? 'border-primary-500 text-gray-900'
                    : 'border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700',
                ]"
              >
                {{ item.name }}
              </router-link>
            </div>
          </div>
          <div class="flex items-center space-x-4">
            <router-link
              to="/profile"
              class="text-gray-700 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium"
            >
              <div class="flex items-center space-x-2">
                <span>{{ user?.name }}</span>
                <div class="w-8 h-8 bg-primary-100 rounded-full flex items-center justify-center">
                  <span class="text-primary-600 font-semibold text-sm">
                    {{ user?.name?.charAt(0).toUpperCase() }}
                  </span>
                </div>
              </div>
            </router-link>
            <button
              @click="handleLogout"
              class="text-gray-500 hover:text-gray-700 px-3 py-2 rounded-md text-sm font-medium"
            >
              Logout
            </button>
          </div>
        </div>
      </div>
    </nav>

    <main class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      <slot />
    </main>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const router = useRouter()
const authStore = useAuthStore()

const user = computed(() => authStore.user)

const navigation = computed(() => {
  if (authStore.isAdmin) {
    return [
      { name: 'Admin Dashboard', to: '/admin' },
      { name: 'Warehouses', to: '/warehouses' },
    ]
  } else if (authStore.isWarehouseAdmin) {
    return [
      { name: 'Dashboard', to: '/warehouse-admin' },
      { name: 'Warehouses', to: '/warehouses' },
      { name: 'Appointments', to: '/appointments' },
    ]
  } else {
    // Farmer navigation
    return [
      { name: 'Dashboard', to: '/dashboard' },
      { name: 'Warehouses', to: '/warehouses' },
      { name: 'My Appointments', to: '/appointments' },
      { name: 'Deliveries', to: '/deliveries' },
    ]
  }
})

const handleLogout = () => {
  authStore.logout()
  router.push('/login')
}
</script>

// frontend/src/components/Layout.jsx
import React from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

const Layout = ({ children }) => {
  const { user, logout, isFarmer, isWarehouseAdmin, isSystemAdmin } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  const navigation = [
    ...(isFarmer ? [
      { name: 'Dashboard', path: '/farmer/dashboard' },
      { name: 'Appointments', path: '/farmer/appointments' },
      { name: 'Waiting Lists', path: '/farmer/waiting-lists' },
      { name: 'History', path: '/farmer/history' },
      { name: 'Profile', path: '/farmer/profile' }
    ] : []),
    ...(isWarehouseAdmin ? [
      { name: 'Dashboard', path: '/warehouse/dashboard' },
      { name: 'Appointments', path: '/warehouse/appointments' },
      { name: 'Deliveries', path: '/warehouse/deliveries' },
      { name: 'Storage', path: '/warehouse/storage' },
      { name: 'Profile', path: '/warehouse/profile' }
    ] : []),
    ...(isSystemAdmin ? [
      { name: 'Dashboard', path: '/admin/dashboard' },
      { name: 'Warehouse Admins', path: '/admin/warehouse-admins' },
      { name: 'Profile', path: '/admin/profile' }
    ] : [])
  ];

  return (
    <div className="min-h-screen bg-gray-50">
      <nav className="bg-white shadow-sm border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16">
            <div className="flex">
              <div className="flex-shrink-0 flex items-center">
                <span className="text-2xl font-bold text-primary-600">MAHSOULE</span>
              </div>
              <div className="hidden sm:ml-8 sm:flex sm:space-x-8">
                {navigation.map((item) => (
                  <Link
                    key={item.path}
                    to={item.path}
                    className={`inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium ${
                      location.pathname === item.path
                        ? 'border-primary-500 text-gray-900'
                        : 'border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700'
                    }`}
                  >
                    {item.name}
                  </Link>
                ))}
              </div>
            </div>
            <div className="flex items-center space-x-4">
              <div className="text-sm text-gray-700">
                <span className="font-medium">{user?.firstName} {user?.lastName}</span>
                <span className="ml-2 text-gray-500">({user?.role.replace('_', ' ')})</span>
              </div>
              <button
                onClick={handleLogout}
                className="btn btn-secondary text-sm"
              >
                Logout
              </button>
            </div>
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
        {children}
      </main>
    </div>
  );
};

export default Layout;
